create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  created_by_user_id bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (created_by_user_id, name)
);

create table if not exists public.class_students (
  class_id bigint not null references public.classes(id) on delete cascade,
  student_id bigint not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (class_id, student_id),
  unique (student_id)
);

create index if not exists classes_creator_idx
on public.classes (created_by_user_id, name);

create index if not exists class_students_class_idx
on public.class_students (class_id, student_id);
