-- Course-level final assessment and certificate migration.
-- Existing questions/question_attempts remain practice-only learning records.

alter table public.courses
add column if not exists retest_cooldown_minutes integer not null default 60,
add column if not exists final_question_count integer not null default 10,
add column if not exists certificate_show_score boolean not null default true;

update public.courses
set passing_score = 70
where passing_score is null;

alter table public.courses
alter column passing_score set default 70;

update public.courses
set require_passing_score = true;

create table if not exists public.final_assessment_questions (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  question_text text not null,
  options_json jsonb not null default '[]'::jsonb,
  answer text not null,
  explanation text,
  knowledge_point_titles jsonb not null default '[]'::jsonb,
  bank_version integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists final_assessment_questions_course_active_idx
on public.final_assessment_questions(course_id, is_active, bank_version);

create table if not exists public.final_assessment_attempts (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  attempt_number integer not null,
  passing_score numeric(5,2) not null,
  score numeric(5,2),
  total_questions integer not null default 0,
  correct_questions integer not null default 0,
  passed boolean not null default false,
  status text not null default 'in_progress',
  question_ids jsonb not null default '[]'::jsonb,
  answers_json jsonb not null default '{}'::jsonb,
  results_json jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  retry_available_at timestamptz,
  unique(student_id, course_id, attempt_number)
);

create index if not exists final_assessment_attempts_student_course_idx
on public.final_assessment_attempts(student_id, course_id, started_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'final_assessment_attempts_status_check'
      and conrelid = 'public.final_assessment_attempts'::regclass
  ) then
    alter table public.final_assessment_attempts
    add constraint final_assessment_attempts_status_check
    check (status in ('in_progress', 'passed', 'failed'));
  end if;
end $$;

create sequence if not exists public.course_certificate_code_seq;

create or replace function public.next_course_certificate_code()
returns text
language sql
as $$
  select 'CERT-' || to_char(current_date, 'YYYY') || '-' ||
         lpad(nextval('public.course_certificate_code_seq')::text, 6, '0');
$$;

create table if not exists public.course_certifications (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  credits_awarded numeric(6,2) not null default 0,
  status text not null default 'eligible',
  earned_at timestamptz not null default now(),
  certificate_code text,
  unique(student_id, course_id)
);

alter table public.course_certifications
add column if not exists final_attempt_id bigint references public.final_assessment_attempts(id) on delete set null,
add column if not exists learning_hours numeric(8,2) not null default 0,
add column if not exists final_score numeric(5,2),
add column if not exists student_name text,
add column if not exists course_name text,
add column if not exists show_final_score boolean not null default true;

alter table public.course_certifications
alter column certificate_code set default public.next_course_certificate_code();

update public.course_certifications
set certificate_code = public.next_course_certificate_code()
where certificate_code is null or btrim(certificate_code) = '';

create unique index if not exists course_certifications_code_key
on public.course_certifications(certificate_code);

notify pgrst, 'reload schema';
