create table if not exists question_attempts (
  id bigint generated by default as identity primary key,
  student_id bigint not null references users(id) on delete cascade,
  lecture_id bigint not null references lectures(id) on delete cascade,
  question_id bigint not null references questions(id) on delete cascade,
  selected_answer text not null,
  is_correct boolean not null,
  video_time double precision,
  answered_at timestamptz not null default now()
);

create index if not exists question_attempts_student_lecture_idx
on question_attempts (student_id, lecture_id);

create index if not exists question_attempts_question_idx
on question_attempts (question_id);
