alter table public.questions
add column if not exists question_type text not null default 'original';

alter table public.questions
add column if not exists source_question_id bigint null references public.questions(id) on delete cascade;

create index if not exists questions_question_type_idx
on public.questions (question_type);

create index if not exists questions_source_question_id_idx
on public.questions (source_question_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'questions_question_type_check'
      and conrelid = 'public.questions'::regclass
  ) then
    alter table public.questions
    add constraint questions_question_type_check
    check (question_type in ('original', 'extension'));
  end if;
end $$;

alter table public.question_attempts
add column if not exists attempt_type text not null default 'initial';

alter table public.question_attempts
add column if not exists attempt_number integer not null default 1;

alter table public.question_attempts
add column if not exists retest_session_id bigint null;

create index if not exists question_attempts_attempt_type_idx
on public.question_attempts (attempt_type);

create table if not exists public.retest_sessions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  original_accuracy double precision,
  retest_accuracy double precision,
  pass_threshold double precision not null default 0.7,
  total_questions integer not null default 0,
  correct_questions integer not null default 0,
  status text not null default 'in_progress',
  attempt_number integer not null default 1,
  question_ids jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz null
);

create index if not exists retest_sessions_student_course_idx
on public.retest_sessions (student_id, course_id, started_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'retest_sessions_status_check'
      and conrelid = 'public.retest_sessions'::regclass
  ) then
    alter table public.retest_sessions
    add constraint retest_sessions_status_check
    check (status in ('in_progress', 'passed', 'failed'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'question_attempts_attempt_type_check'
      and conrelid = 'public.question_attempts'::regclass
  ) then
    alter table public.question_attempts
    add constraint question_attempts_attempt_type_check
    check (attempt_type in ('initial', 'retest'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'question_attempts_retest_session_id_fkey'
      and conrelid = 'public.question_attempts'::regclass
  ) then
    alter table public.question_attempts
    add constraint question_attempts_retest_session_id_fkey
    foreign key (retest_session_id)
    references public.retest_sessions(id)
    on delete set null;
  end if;
end $$;
